language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - git remote rm origin
  - git remote add origin https://NuoHui:$GITHUB_TOKEN@github.com/NuoHui/easy-cli.git
  - git symbolic-ref HEAD refs/heads/master
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$AUTH_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
after_success:
  - npm version patch -m '[patch]'
  - git push origin master --tag
