language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
install:
  - npm install
script: npm run lint
before_deploy:
  - ./node_modules/.bin/patch-version
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key:
    secure: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest
